test/helpers: use `RetryOnConflict` for node writes
I saw this race in a PR:

```
Error:      	Expected nil, but got: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"Operation cannot be fulfilled on nodes \"ci-op-pjcj27z5-ff089-5jw6w-worker-b-dhsmk\": the object has been modified; please apply your changes to the latest version and try again", Reason:"Conflict", Details:(*v1.StatusDetails)(0xc000450cc0), Code:409}}
Test:       	TestKernelType
```

A general problem with our tests is that they tend to be written
in "one shot" mode but in cases like this we need to do retries
and reconciliation.

(Actually in this case it'd be better to format a strategic patch
 I think, but for now let's just do a standard `RetryOnConflict`
 as is done elsewhere)