controller: fix missing args for logs
```
$ go test ./...
pkg/controller/bootstrap/bootstrap.go:87: Infof call needs 1 arg but has 2 args
?       github.com/openshift/machine-config-operator/cmd/common [no test files]
?       github.com/openshift/machine-config-operator/cmd/machine-config-controller      [no test files]
?       github.com/openshift/machine-config-operator/cmd/machine-config-daemon  [no test files]
?       github.com/openshift/machine-config-operator/cmd/machine-config-operator        [no test files]
?       github.com/openshift/machine-config-operator/cmd/machine-config-server  [no test files]
?       github.com/openshift/machine-config-operator/cmd/setup-etcd-environment [no test files]
?       github.com/openshift/machine-config-operator/lib        [no test files]
ok      github.com/openshift/machine-config-operator/lib/resourceapply  0.038s
ok      github.com/openshift/machine-config-operator/lib/resourcemerge  0.023s
?       github.com/openshift/machine-config-operator/lib/resourceread   [no test files]
ok      github.com/openshift/machine-config-operator/pkg/apis   0.025s
ok      github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1      0.024s
pkg/controller/render/render_controller.go:203: Error call has possible formatting directive %v
pkg/controller/render/render_controller.go:240: Error call has possible formatting directive %v
ok      github.com/openshift/machine-config-operator/pkg/controller/node        0.032s
FAIL    github.com/openshift/machine-config-operator/pkg/controller/render [build failed]
ok      github.com/openshift/machine-config-operator/pkg/controller/template    0.110s
ok      github.com/openshift/machine-config-operator/pkg/daemon 0.012s
ok      github.com/openshift/machine-config-operator/pkg/operator       0.084s
ok      github.com/openshift/machine-config-operator/pkg/server 0.085s
$ go version
go version go1.11.2 linux/amd64
```

Not sure why the ci didn't complain :/